# Generated by Django 4.1.5 on 2023-02-01 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_test1"),
    ]

    operations = [
        migrations.DeleteModel(name="Test1",),
    ]
